### ISSUE TITLE
Code Clinic

### ISSUE THREAD

**Issue by hwayne** [chihacknight/breakout-groups#7]
**About the group:** We're here to help with any technical issues you might have. Whether it's debugging some code, setting up Heroku, designing a database table, or anything else that's causing you problems, we'll either help you solve it or find someone who can.

**Group Leaders:** [Hillel Wayne](mailto:hwayne@gmail.com), [Karl Fogel](http://www.red-bean.com/kfogel/contact)

**Who we're looking for:** Anyone, regardless of skill level, who likes helping other people.

**Where we meet:** Usually we start out in the main room and spread out from there. If you want to ask a question, come find one of us: we're always available.

**Slack channel:** Always on at [chihacknight.slack.com/messages/code-clinic/](https://chihacknight.slack.com/messages/code-clinic/)

**Comment by Schmittyapolis** [comment]
I'm interested in joining this group. What do I need to do to accomplish this?

**Comment by kfogel** [comment]
Hi, Scott.  I think you're in it :-).  All you have to do is stand up when the Code Clinic announcement happens at Hack Night, so people see what you look like and will be able to seek you out during the breakout session time.  Welcome to Code Clinic!

**Comment by Schmittyapolis** [comment]
@kfogel will do - sounds good!

**Comment by kfogel** [comment]
Hey, @yjkogan, thanks for joining Code Clinic at Hack Night tonight!

**Comment by yjkogan** [comment]
Yep! I'd love to help as time permits! For the next bit I'm swamped, but can try to be available in off-hours on slack or w/e :)

**Comment by Schmittyapolis** [comment]
So, I've taken html/CSS classes in the past but haven't kept up with the new changes. Going through Free Code Camp now. I only have two pens on codepen.io at this point, but would appreciate any help regarding getting the nav to scroll (rather than jump) and setting up a gallery where once you click on a thumbnail, the full graphic pops up in a new window and you are then able to move from one sample to the next across all projects. I'm also up for meeting beyond Chicago Hack Nights, say one week night a week, to code/learn/teach others that are learning as well. Dunno if that interests anyone - I'm in Oak Park.

**Comment by kfogel** [comment]
Hey, @Schmittyapolis.  Hmmm, your question makes me wonder if setting up a dedicate New Coders group would be a good idea.  Not necessarily a new breakout group (b/c there are already so many :-) ), but just as part of Code Clinic.  I think these things are so much easier to learn in groups, for all sorts of reasons.  I can't be at Chi Hack Night tonight, but if you want to propose it tonight go for it!  Otherwise I may do so the next time I attend.

Regarding the specific problems w/ nav scrolling and thumbnail clicking: maybe show the specific code to someone from Code Clinic tonight and see how far you can get?

**Comment by richagg** [comment]
What coding environments do you work in? It would be helpful to know what skills you would like new joinees to have. I'm keen to join but don't know what I can help with and also what I can learn here.

**Comment by kfogel** [comment]
Hey @yjkogan @derekeder @hwayne et al:

Raised a [thread in Slack](https://chihacknight.slack.com/archives/C08SX8P8Q/p1527191321000235) about considering shuttering Code Clinic as a Tuesday night breakout group, just FYI.

**Comment by kfogel** [comment]
Closing as per the above thread.  I'll send a mail to organizers and hosts too; if that leads to a different conclusion than we can re-open this breakout group, but right now among those who have participated in the discussion it looks like consensus is to close.

**Comment by kfogel** [comment]
@derekeder I noticed you re-opened the group.  I'm curious why?  (Not objecting, just curious.)

**Comment by derekeder** [comment]
I think I reopened this because it was announced that night. Feel free to close it again if you'd like!

**Comment by kfogel** [comment]
Gotcha.  Okay, closing -- I think we have enough roving help available now that we don't need a formal Code Clinic group (and formal requests for help *to* Code Clinic have been rare in the past year or two).  The `code clinic` Slack channel can stay IMHO; no reason to to continue providing an online help forum that people have found useful.

Sorry I can't be there tonight; I hope the presentation goes well and see you all soon.
