### ISSUE TITLE
ChiCalls: Website for Calling Representatives on a Local Level 

### ISSUE THREAD

**Issue by rebeccafishman** [chihacknight/breakout-groups#90]
### About the group

****Looking for people with Wordpress experience ****

We are creating a website to make it easier for people in Chicago to call their aldermen about issues relevant to their ward. 

We are aiming to expand upon existing resources that help people find information on their aldermen by also providing ward-specific calls-to-action generated by local community organizations. We also aim to include corresponding scripts that could be used as suggestions or templates for what to say in the calls.

The website would search a Chicago address, then output the ward, phone number and name of alderman along with current ward-specific issues or calls to action and suggested scripts.

This would amplify the direct concerns of people in the community as well as centralize the calls-to-action in a convenient format to make it easier for people to contact their alderman about the issues that matter to them.

### Group leaders
Rebecca Fishman
Becca Quick
Frances Giguette

### Who we're looking for
All are welcome!

### Tools
Wordpress
JavaScript
leaflet
Node.js

### Relevant Links
Check out our git here: https://github.com/rebeccafishman/chi-calls-ii

https://5calls.org/ is a great website for calling state representatives.  The concept of the website we are creating is similar to 5calls but with a sole focus on local Chicago politics.

http://bluestlie.com/ is a website with a similar functionality to the site we are building. We are basing our backend on this site and expanding its content to include a multitude of issues.

Also check out some cool resources on Chicago politics in the comments [below](https://github.com/chihacknight/breakout-groups/issues/90#issuecomment-291741896
)!

### Where we meet
Mainly the cafeteria

### Thinking of joining us?
For more information, check out [Chi Calls 101](https://docs.google.com/document/d/1Y8F20lPy1uCbPQUv2bctqTwk_zWniM61ndJKKRvay7Y/edit?usp=sharing)!

**Comment by stevevance** [comment]
Here are two websites for that information that have already been created:
[My Reps](http://myreps.datamade.us/#/?address=121%20N%20LaSalle%20St%2C%20Chicago%2C%20IL%2C%20United%20States)
[Chicago Councilmatic](https://chicago.councilmatic.org/council-members/)

**Comment by ASchneidman** [comment]
Here's our github:
https://github.com/ASchneidman/ChicagoCalls

**Comment by derekeder** [comment]
Thanks for sharing those links @stevevance! My company DataMade built both of those sites & they're both open source. Happy to talk about them and give pointers.

**Comment by rebeccafishman** [comment]
Yes, thank you @stevevance! I was not aware of these sites and will edit the group description accordingly. @derekeder, we would love to talk to you about your company's sites. Potentially at the next Chi Hack Night? Also as a clarification, in addition to a searchable database with the alderman's information, we hope to incorporate ward-specific calls to action from Chicago activist groups with scripts as suggestions for calls to make.

**Comment by derekeder** [comment]
Cool - happy to talk about this at hack night next week @rebeccafishman

**Comment by ASchneidman** [comment]
@rebeccafishman I won't be able to make it next Tuesday but Tuesdays for the rest of the year should be fine after next week.

**Comment by natalieleroy** [comment]
Hi there! I was at the last hack night but did not get a chance to connect with this group. 
I'm currently working on a line of clothes featuring portraits of representatives and their contact information to be posted on threadless.com as a non-profit shop. The ultimate goal is for every purchase, $7-8 will be sent to the ACLU. Currently I have the representatives of Ohio and California done, and I'm looking to recruit more! If you're up for it, I'd love to gather some information and make a special Chicago Edition. Hopefully it could help! Please email me directly, otherwise I will be at the next hacknight. Thanks,
Natalie.

**Comment by ASchneidman** [comment]
I did a lot of research on Flask and I implemented a form for entering an address using POST and Flask. I also put in bootstrap. I committed all the new stuff to the master.

**Comment by rebeccafishman** [comment]
@ASchneidman Great! I'll check it out

**Comment by ASchneidman** [comment]
@rebeccafishman I can't make it tonight or next Tuesday night but I just wanted to reiterate that the stuff I uploaded to the repository doesn't need to be the way we go about this. Feel free to totally change the framework.

**Comment by derekeder** [comment]
Here's some resources on the history and function of Chicago City Council that may be useful for this project:

### [Sweet Home Chicago: The Story of an Affordable Housing Campaign](http://www.issuelab.org/resource/sweet_home_chicago_the_story_of_an_affordable_housing_campaign)
The Sweet Home Chicago (SHC) Coalition was comprised of nine community organizations and two labor unions that conducted a two and a half year campaign that resulted in passage of the Vacant Building TIF Purchase Rehab Program on May 4, 2011. This ordinance is one of the very few pieces of legislation to benefit low-income people that passed during Mayor Richard Daley's 22 years in office. 

### [Rogues, Rebels, And Rubber Stamps: The Politics Of The Chicago City Council, 1863 To The Present](https://www.amazon.com/Rogues-Rebels-Rubber-Stamps-Challenges/dp/0813397634)
In Rogues, Rebels, and Rubber Stamps, Dick Simpson challenges and recasts current theories of Regime Politics as he chronicles the dramatic story of the civic wars in the Chicago City Council since the civil war. At the same time, the author provides a window into the broader struggle for democracy and justice.Simpson points out that through analyzing city council floor fights, battles at the ballot box, and street demonstrations, one can begin to see certain patterns of conflict emerge. These patterns demonstrate that before the Great Depression, fragmented city councils were dominant. The author also discusses how since the Democrats seized control of Chicago government after the Great Depression, Rubber Stamp City Councils have been predominant, although they have been punctuated by brief eras of council wars and chaos. This book is important for anyone wanting to understand the nature of these battles as a guideline for America's future, and is well suited for courses in urban politics, affairs and history.

### [Aldermanic Privilege, Encyclopedia of Chicago](http://www.encyclopedia.chicagohistory.org/pages/2197.html)
Aldermanic privilege refers to the power of Chicago city council members (aldermen) to initiate or block city council or city government actions concerning their own wards. Sometimes written into official council rules, it is often based on unwritten understandings among members or on arrangements with city administrators who find it expedient to routinely comply with aldermanic requests.

### [Chicago City Council, Clout Wiki](http://clout.wiki/Chicago_City_Council)
Overview of Chicago City Council and bios on its members.

### Several articles on the "Council Wars"
* http://www.encyclopedia.chicagohistory.org/pages/342.html
* https://en.wikipedia.org/wiki/Council_Wars
* http://www.csmonitor.com/1986/0501/awind.html

**Comment by derekeder** [comment]
is this breakout group still active? if not, let's close it for now

**Comment by rebeccafishman** [comment]
@derekeder No, it is not.  I've moved to a different city - sorry I didn't close it earlier.  Thanks so much for the opportunity to work on this project at Chi Hack Night, and if anyone ever embarks on a similar project down the line, I am happy to talk.

**Comment by derekeder** [comment]
@rebeccafishman thanks for the update and best of luck in your new city!
