### ISSUE TITLE
Volunteer Chicago 

### ISSUE THREAD

**Issue by ziegegeist** [chihacknight/breakout-groups#91]
### About the group
We want to connect people with volunteer opportunities best suited for them and connect organizations with good volunteers. [volunteerchicago.org](url)

### Group leaders
Joel Inwood and YOU!

### Who we're looking for
Check out the GitHub Issues. Pretty basic stuff right now. [https://github.com/ziegegeist/volunteerchicago/issues](url)

### Tools
Jekyll, MailChimp and Twitter

### Relevant Links
volunteerchicago.org

### Where we meet
The cafeteria?

**Comment by yjkogan** [comment]
Hey @ziegegeist! I just got an email from someone who works with lawyer at the Immigration clinic at DePaul Law School, asking if someone could help them create "a system that would facilitate the matching of volunteers and  volunteer opportunities that is secure." Do you think this matches what you're trying to do? If so, would it be helpful to put you in touch?

**Comment by ziegegeist** [comment]
I'm still not sure what I'm doing or how to do it, so it would be great to talk to someone who needs something! Thanks!

**Comment by yjkogan** [comment]
@ziegegeist awesome! What's the best way for me to connect you? Right now I only have their email.

**Comment by ziegegeist** [comment]
It's just ziegegeist at gmal

**Comment by yjkogan** [comment]
Also, not sure if this is helpful but someone mentioned this tonight at tech solidarity: http://chicagoactivism.org/

**Comment by tutormentor** [comment]
I left some comments for Joel in the Slack group.  In your planning, I urge you to review volunteer matching resources already available, and determine how what you want to build will fill a void, or add value.  

View this concept map, to see existing volunteer matching platforms available to people in Chicago. http://tinyurl.com/TMI-Volunteer-Opportunities  A few of these are sites I have managed for many years to help identify and draw support to non-school tutor and mentor programs in the Chicago region.  Rather than create something new, I'd love to have some tech folks adopt what I've been doing and partner with me to do it better.

However, I only focus on youth serving programs. There are many other service categories where people might volunteer.  If you search the portal at the ServeIllinois commission, or at Volunteer Match, you can search by category to find opportunities within a 5, 10 or 15 mile radius, but you cannot find maps showing where different types of service are most needed, and which operate in specific areas. Borrowing from what I've been doing, you might build a portal that does that for other sectors.

Or, you might think completely different.  While I host maps showing indicators of where tutor/mentor programs are needed, and what programs are available in different areas, my goal is to help each program build a network of volunteer support that enables each to offer a broader, longer-term, range of support to  youth.  If you look at this "talent needed" concept map you'll see that each program needs a range of talents to support it's operations, and its youth. http://tinyurl.com/TMI-TalentNeeded

Since ChiHackNight mobilizes tech people, why not develop a service that encourages tech people to volunteer talent in different programs, then create a map showing where these people are volunteering, and in what capacity (direct service, board member, tech support, etc.).  

Finally, please keep in mind that the platform is only a tool, which must be updated regularly. Getting people to use that tool to support growth of non-profits throughout the city, requires an on-going marketing and communications program, a training capacity, and an evaluation capacity.  I created this 4-part strategy concept map to illustrate this. http://tinyurl.com/TMI-4-Pt-Strategy

Step 1 includes building the portal, and filling it with volunteer opportunities.  Step 2 is creating on-going communications that encourages more potential volunteers to look at the information in the portal. Step 3 is a facilitation process, helping volunteers understand all the ways they might be involved, and all the places where they are needed. It also is intended to teach leaders in sectors (like the tech sector) ways they can mobilize members to support programs across the city.  Step 4 is a call to action, like weekly advertising, that motivates people to actually take the steps to get involved. It also is a step where you try to capture information about who got involved, where they got involved, etc. so  you can use this understanding in future efforts intended to build a better distribution of volunteer involvement.

Just building a portal is not enough. Thinking through the ways it will be used and evaluated, as I've just suggested, is the way to make sure that what you build has maximum impact.

I'd be happy to meet with you and give you a tour of my own mapping efforts, to show what I've been trying to do, what works and what does not, and what's still on the drawing board that I've not found resources to implement.

**Comment by ziegegeist** [comment]
@tutormentor I won't be at hack night tonight, but I'll be there next week. Want to meet up then?

**Comment by tutormentor** [comment]
Hi Joel,

We can meet up next week or meet up some time in between.

I don't bring a laptop with me to hacknight, so hope you'll have one with
you.

Dan
