### ISSUE TITLE
Transit Talk 

### ISSUE THREAD

**Issue by vkoves** [chihacknight/breakout-groups#93]
## About the group
Caravan is a platform that democratizes the flow of information about issues that riders encounter on public transit. Based on Ruby on Rails and open GTFS data, our team is building an app that can be adapted to thousands of train, bus, trolley, boat, and other types of transit lines around the world, allowing riders to tailor their trips based on reports from other users about cleanliness, delays, crime, and more. Caravan seeks to empower transit users to better their experience and pressure transit administrators to address repetitive issues in a public, data-backed fashion, making all its data available to those seeking to push change forward at the local level.

We have a channel in the ChiHackNight Slack, **#caravan-transit**.

## Group leaders
Viktor Köves, Jannie Lung, Ranjani Prabhakar, Soren Spicknall

## Who we're looking for
Ruby on Rails programmers, mapping and transit data enthusiasts, community outreach experts, and anybody who believes in what we're doing!

## Tools
Ruby on Rails
GTFS Data
MySQL
HTML, CSS, and a dash of jQuery  

## Relevant Links
The site and all published work lives on Heroku at the moment, at [caravan-transit.herokuapp.com](https://caravan-transit.herokuapp.com). Note that this does not always reflect most recent changes and is also a deployed version of the modular Caravan system with data loaded in for the CTA. 

All repository files can be found at [CaravanTransit/Caravan-App](https://github.com/CaravanTransit/Caravan-App) on GitHub. 

## Where we meet
The back right corner of the atrium (where the main presentation is)

**Comment by stevevance** [comment]
I've been working with Mapzen to build the world's most complete, and open source, transit database called [Transitland](https://transit.land).

**Comment by AcademyInPeril** [comment]
We won't be meeting tonight, but pay attention to the #transit-network channel in the ChiHackNight Slack for work that we'll be doing throughout the next week!

**Comment by derekeder** [comment]
FYI, there was a project in 2011/2012 around classifying tweets related to CTA issues. I can't find a link to it, but @corynissen worked on it and may have some thoughts to add to this project.

**Comment by corynissen** [comment]
We did classify CTA tweets way back, but that was before my github days, so I don't think I have any of that stuff any more. It doesn't matter too much, because the Twitter geocoding part of their API is worse now than it was then, so that old project wouldn't really work these days. [Here's](https://twittercommunity.com/t/search-api-returning-very-sparse-geocode-results/27998) a thread about this issue. Any how, the idea was that we'd look at tweets with "CTA" in them in the chicago area (since CTA is used elsewhere) and try to identify tweets talking about delays, cleanliness issues, and other things. It did work fairly well, as people were doing a lot of complaining about the CTA on twitter. Good luck with your project.

**Comment by vkoves** [comment]
Closing so Soren can make a new one
